// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieApp.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230823133439_Feed_data")]
    partial class Feed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dislike")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Like")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 1 title"
                        },
                        new
                        {
                            Id = 2,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 2 title"
                        },
                        new
                        {
                            Id = 3,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 3 title"
                        },
                        new
                        {
                            Id = 4,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 4 title"
                        },
                        new
                        {
                            Id = 5,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 5 title"
                        },
                        new
                        {
                            Id = 6,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 6 title"
                        },
                        new
                        {
                            Id = 7,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 7 title"
                        },
                        new
                        {
                            Id = 8,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 8 title"
                        },
                        new
                        {
                            Id = 9,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 9 title"
                        },
                        new
                        {
                            Id = 10,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 10 title"
                        },
                        new
                        {
                            Id = 11,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 11 title"
                        },
                        new
                        {
                            Id = 12,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 12 title"
                        },
                        new
                        {
                            Id = 13,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 13 title"
                        },
                        new
                        {
                            Id = 14,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 14 title"
                        },
                        new
                        {
                            Id = 15,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 15 title"
                        },
                        new
                        {
                            Id = 16,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 16 title"
                        },
                        new
                        {
                            Id = 17,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 17 title"
                        },
                        new
                        {
                            Id = 18,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 18 title"
                        },
                        new
                        {
                            Id = 19,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 19 title"
                        },
                        new
                        {
                            Id = 20,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 20 title"
                        },
                        new
                        {
                            Id = 21,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 21 title"
                        },
                        new
                        {
                            Id = 22,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 22 title"
                        },
                        new
                        {
                            Id = 23,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 23 title"
                        },
                        new
                        {
                            Id = 24,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 24 title"
                        },
                        new
                        {
                            Id = 25,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 25 title"
                        },
                        new
                        {
                            Id = 26,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 26 title"
                        },
                        new
                        {
                            Id = 27,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 27 title"
                        },
                        new
                        {
                            Id = 28,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 28 title"
                        },
                        new
                        {
                            Id = 29,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 29 title"
                        },
                        new
                        {
                            Id = 30,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 30 title"
                        },
                        new
                        {
                            Id = 31,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 31 title"
                        },
                        new
                        {
                            Id = 32,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 32 title"
                        },
                        new
                        {
                            Id = 33,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 33 title"
                        },
                        new
                        {
                            Id = 34,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 34 title"
                        },
                        new
                        {
                            Id = 35,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 35 title"
                        },
                        new
                        {
                            Id = 36,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 36 title"
                        },
                        new
                        {
                            Id = 37,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 37 title"
                        },
                        new
                        {
                            Id = 38,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 38 title"
                        },
                        new
                        {
                            Id = 39,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 39 title"
                        },
                        new
                        {
                            Id = 40,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 40 title"
                        },
                        new
                        {
                            Id = 41,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 41 title"
                        },
                        new
                        {
                            Id = 42,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 42 title"
                        },
                        new
                        {
                            Id = 43,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 43 title"
                        },
                        new
                        {
                            Id = 44,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 44 title"
                        },
                        new
                        {
                            Id = 45,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 45 title"
                        },
                        new
                        {
                            Id = 46,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 46 title"
                        },
                        new
                        {
                            Id = 47,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 47 title"
                        },
                        new
                        {
                            Id = 48,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 48 title"
                        },
                        new
                        {
                            Id = 49,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 49 title"
                        },
                        new
                        {
                            Id = 50,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 50 title"
                        },
                        new
                        {
                            Id = 51,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 51 title"
                        },
                        new
                        {
                            Id = 52,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 52 title"
                        },
                        new
                        {
                            Id = 53,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 53 title"
                        },
                        new
                        {
                            Id = 54,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 54 title"
                        },
                        new
                        {
                            Id = 55,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 55 title"
                        },
                        new
                        {
                            Id = 56,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 56 title"
                        },
                        new
                        {
                            Id = 57,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 57 title"
                        },
                        new
                        {
                            Id = 58,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 58 title"
                        },
                        new
                        {
                            Id = 59,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 59 title"
                        },
                        new
                        {
                            Id = 60,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 60 title"
                        },
                        new
                        {
                            Id = 61,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 61 title"
                        },
                        new
                        {
                            Id = 62,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 62 title"
                        },
                        new
                        {
                            Id = 63,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 63 title"
                        },
                        new
                        {
                            Id = 64,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 64 title"
                        },
                        new
                        {
                            Id = 65,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 65 title"
                        },
                        new
                        {
                            Id = 66,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 66 title"
                        },
                        new
                        {
                            Id = 67,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 67 title"
                        },
                        new
                        {
                            Id = 68,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 68 title"
                        },
                        new
                        {
                            Id = 69,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 69 title"
                        },
                        new
                        {
                            Id = 70,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 70 title"
                        },
                        new
                        {
                            Id = 71,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 71 title"
                        },
                        new
                        {
                            Id = 72,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 72 title"
                        },
                        new
                        {
                            Id = 73,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 73 title"
                        },
                        new
                        {
                            Id = 74,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 74 title"
                        },
                        new
                        {
                            Id = 75,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 75 title"
                        },
                        new
                        {
                            Id = 76,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 76 title"
                        },
                        new
                        {
                            Id = 77,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 77 title"
                        },
                        new
                        {
                            Id = 78,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 78 title"
                        },
                        new
                        {
                            Id = 79,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 79 title"
                        },
                        new
                        {
                            Id = 80,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 80 title"
                        },
                        new
                        {
                            Id = 81,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 81 title"
                        },
                        new
                        {
                            Id = 82,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 82 title"
                        },
                        new
                        {
                            Id = 83,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 83 title"
                        },
                        new
                        {
                            Id = 84,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 84 title"
                        },
                        new
                        {
                            Id = 85,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 85 title"
                        },
                        new
                        {
                            Id = 86,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 86 title"
                        },
                        new
                        {
                            Id = 87,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 87 title"
                        },
                        new
                        {
                            Id = 88,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 88 title"
                        },
                        new
                        {
                            Id = 89,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 89 title"
                        },
                        new
                        {
                            Id = 90,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 90 title"
                        },
                        new
                        {
                            Id = 91,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 91 title"
                        },
                        new
                        {
                            Id = 92,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 92 title"
                        },
                        new
                        {
                            Id = 93,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 93 title"
                        },
                        new
                        {
                            Id = 94,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 94 title"
                        },
                        new
                        {
                            Id = 95,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 95 title"
                        },
                        new
                        {
                            Id = 96,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 96 title"
                        },
                        new
                        {
                            Id = 97,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 97 title"
                        },
                        new
                        {
                            Id = 98,
                            Dislike = 0,
                            Image = "https://images.freeimages.com/images/previews/5eb/movie-clapboard-1184339.jpg",
                            Like = 0,
                            Title = "Movie 98 title"
                        },
                        new
                        {
                            Id = 99,
                            Dislike = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1pJ0eoHXdlJEVeVY0MlJ2kUOYrLHGvpY7yIHl2E4&s",
                            Like = 0,
                            Title = "Movie 99 title"
                        },
                        new
                        {
                            Id = 100,
                            Dislike = 0,
                            Image = "https://www.shutterstock.com/shutterstock/photos/586719869/display_1500/stock-vector-online-cinema-art-movie-watching-with-popcorn-and-film-strip-cinematograph-concept-vintage-retro-586719869.jpg",
                            Like = 0,
                            Title = "Movie 100 title"
                        });
                });

            modelBuilder.Entity("MovieApp.Data.Entities.MovieReaction", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<bool>("Disliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("Liked")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieReactions", (string)null);
                });

            modelBuilder.Entity("MovieApp.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            Password = "35b5d11496a69a14ba81244ab3b02fc2",
                            Uid = new Guid("98baf0de-0bc1-488d-972d-abc28be9ecb1"),
                            Username = "user1"
                        });
                });

            modelBuilder.Entity("MovieApp.Data.Entities.MovieReaction", b =>
                {
                    b.HasOne("MovieApp.Data.Entities.Movie", "Movie")
                        .WithMany("MovieReactions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Data.Entities.User", "User")
                        .WithMany("MovieReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.Movie", b =>
                {
                    b.Navigation("MovieReactions");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.User", b =>
                {
                    b.Navigation("MovieReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
